### ISSUE TITLE
Incorrect(?) hilt version

### ISSUE THREAD

**Issue by akwasiio** [Ezike/MVI_UIComponents#1]
The current 2.28.3-alpha raised build issues on my end so I referenced the official docs and found out that the latest hilt version is 2.28-alpha (this resolved all the build issues I had).

**Comment by Ezike** [comment]
> The current 2.28.3-alpha raised build issues on my end so I referenced the official docs and found out that the latest hilt version is 2.28-alpha (this resolved all the build issues I had). 

The current version is 2.29.1

**Comment by akwasiio** [comment]
Yeah, you are right. Even 2.28.3-alpha actually exists. This is really odd. I figure it has to do with Android Studio. Using 4.2 Canary 11.

**Comment by Ezike** [comment]
yea it does exist lol
