### ISSUE TITLE
Pagination in StarWars API

### ISSUE THREAD

**Issue by alirezaeiii** [Ezike/MVI_UIComponents#3]
You made a nice sample using MVI. The Search history feature is quite interesting. Thank you for that, But as far as I know StarWars API supports pagination. Did you use Paging library to display search items?

**Comment by Ezike** [comment]
Hi, thank you 🙏🏾.
I didn't implement lazy loading kind of pagination like the paging library does.
I used recursion to pull all the data in one call. Yea it doesn't really scale but was sorta fun

**Comment by Ezike** [comment]
> You made a nice sample using MVI. The Search history feature is quite interesting. Thank you for that, But as far as I know StarWars API supports pagination. Did you use Paging library to display search items?

Hi, thank you 🙏🏾.
I didn't implement the lazy loading pagination like the paging library does.
I recursively pull the data from the api if a next page is available. 
https://github.com/Ezike/StarWarsSearch-MVI/blob/main/lib_character_search/src/main/java/com/ezike/tobenna/starwarssearch/lib_character_search/remote/impl/SearchRemoteImpl.kt

Yea it doesn't scale but it was sorta fun 😸

**Comment by alirezaeiii** [comment]
Considering that StarWars API does not need to load many items and it is always limited to a few characters, I agree that you had a nice idea here. Thank you for sharing.
